# Generated by Django 4.0.5 on 2022-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=30)),
                ('card_expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fast_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vehicle_no', models.IntegerField()),
                ('registered_bank', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
