# Generated by Django 4.0.5 on 2022-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fast_tag',
            name='vehicle_no',
            field=models.CharField(max_length=30),
        ),
    ]
